# -- coding: utf-8 --

# Form implementation generated from reading ui file 'interfaz.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName("mainWindow")
        mainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(mainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 40, 321, 201))
        self.groupBox.setObjectName("groupBox")
        self.lb1 = QtWidgets.QLabel(self.groupBox)
        self.lb1.setGeometry(QtCore.QRect(10, 40, 121, 16))
        self.lb1.setObjectName("lb1")
        self.cmb1 = QtWidgets.QComboBox(self.groupBox)
        self.cmb1.setGeometry(QtCore.QRect(10, 70, 181, 22))
        self.cmb1.setObjectName("cmb1")
        self.lb2 = QtWidgets.QLabel(self.groupBox)
        self.lb2.setGeometry(QtCore.QRect(10, 110, 111, 16))
        self.lb2.setObjectName("lb2")
        self.lb3 = QtWidgets.QLabel(self.groupBox)
        self.lb3.setGeometry(QtCore.QRect(10, 150, 111, 16))
        self.lb3.setObjectName("lb3")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(20, 270, 120, 80))
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 370, 301, 141))
        self.groupBox_3.setObjectName("groupBox_3")
        self.btn1 = QtWidgets.QPushButton(self.groupBox_3)
        self.btn1.setGeometry(QtCore.QRect(0, 90, 75, 23))
        self.btn1.setObjectName("btn1")
        self.btn2 = QtWidgets.QPushButton(self.groupBox_3)
        self.btn2.setGeometry(QtCore.QRect(90, 90, 75, 23))
        self.btn2.setObjectName("btn2")
        self.btn3 = QtWidgets.QPushButton(self.groupBox_3)
        self.btn3.setGeometry(QtCore.QRect(190, 90, 75, 23))
        self.btn3.setObjectName("btn3")
        mainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mainWindow)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        _translate = QtCore.QCoreApplication.translate
        mainWindow.setWindowTitle(_translate("mainWindow", "Vectorial"))
        self.groupBox.setTitle(_translate("mainWindow", "Entrada de información "))
        self.lb1.setText(_translate("mainWindow", "Seleccione shapefile"))
        self.lb2.setText(_translate("mainWindow", "Sistema de referencia"))
        self.lb3.setText(_translate("mainWindow", "Numero de atributos"))
        self.groupBox_2.setTitle(_translate("mainWindow", "Geoprocesos"))
        self.groupBox_3.setTitle(_translate("mainWindow", "Salida"))
        self.btn1.setText(_translate("mainWindow", "Ayuda"))
        self.btn2.setText(_translate("mainWindow", "Cancelar"))
        self.btn3.setText(_translate("mainWindow", "Ejecutar"))


if __name__ == "_main_":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainWindow = QtWidgets.QMainWindow()
    ui = Ui_mainWindow()
    ui.setupUi(mainWindow)
    mainWindow.show()
    sys.exit(app.exec_())